/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __NETWORKSPEEDDBUS_H__
#define __NETWORKSPEEDDBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for arindamsen95.NetworkSpeed */

#define TYPE_ARINDAMSEN95_NETWORK_SPEED (arindamsen95_network_speed_get_type ())
#define ARINDAMSEN95_NETWORK_SPEED(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED, Arindamsen95NetworkSpeed))
#define IS_ARINDAMSEN95_NETWORK_SPEED(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED))
#define ARINDAMSEN95_NETWORK_SPEED_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED, Arindamsen95NetworkSpeedIface))

struct _Arindamsen95NetworkSpeed;
typedef struct _Arindamsen95NetworkSpeed Arindamsen95NetworkSpeed;
typedef struct _Arindamsen95NetworkSpeedIface Arindamsen95NetworkSpeedIface;

struct _Arindamsen95NetworkSpeedIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_download) (
    Arindamsen95NetworkSpeed *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_upload) (
    Arindamsen95NetworkSpeed *object,
    GDBusMethodInvocation *invocation);

};

GType arindamsen95_network_speed_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *arindamsen95_network_speed_interface_info (void);
guint arindamsen95_network_speed_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void arindamsen95_network_speed_complete_get_download (
    Arindamsen95NetworkSpeed *object,
    GDBusMethodInvocation *invocation,
    gdouble speed);

void arindamsen95_network_speed_complete_get_upload (
    Arindamsen95NetworkSpeed *object,
    GDBusMethodInvocation *invocation,
    gdouble speed);



/* D-Bus method calls: */
void arindamsen95_network_speed_call_get_download (
    Arindamsen95NetworkSpeed *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean arindamsen95_network_speed_call_get_download_finish (
    Arindamsen95NetworkSpeed *proxy,
    gdouble* out_speed,
    GAsyncResult *res,
    GError **error);

gboolean arindamsen95_network_speed_call_get_download_sync (
    Arindamsen95NetworkSpeed *proxy,
    gdouble* out_speed,
    GCancellable *cancellable,
    GError **error);

void arindamsen95_network_speed_call_get_upload (
    Arindamsen95NetworkSpeed *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean arindamsen95_network_speed_call_get_upload_finish (
    Arindamsen95NetworkSpeed *proxy,
    gdouble* out_speed,
    GAsyncResult *res,
    GError **error);

gboolean arindamsen95_network_speed_call_get_upload_sync (
    Arindamsen95NetworkSpeed *proxy,
    gdouble* out_speed,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY (arindamsen95_network_speed_proxy_get_type ())
#define ARINDAMSEN95_NETWORK_SPEED_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY, Arindamsen95NetworkSpeedProxy))
#define ARINDAMSEN95_NETWORK_SPEED_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY, Arindamsen95NetworkSpeedProxyClass))
#define ARINDAMSEN95_NETWORK_SPEED_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY, Arindamsen95NetworkSpeedProxyClass))
#define IS_ARINDAMSEN95_NETWORK_SPEED_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY))
#define IS_ARINDAMSEN95_NETWORK_SPEED_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ARINDAMSEN95_NETWORK_SPEED_PROXY))

typedef struct _Arindamsen95NetworkSpeedProxy Arindamsen95NetworkSpeedProxy;
typedef struct _Arindamsen95NetworkSpeedProxyClass Arindamsen95NetworkSpeedProxyClass;
typedef struct _Arindamsen95NetworkSpeedProxyPrivate Arindamsen95NetworkSpeedProxyPrivate;

struct _Arindamsen95NetworkSpeedProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  Arindamsen95NetworkSpeedProxyPrivate *priv;
};

struct _Arindamsen95NetworkSpeedProxyClass
{
  GDBusProxyClass parent_class;
};

GType arindamsen95_network_speed_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Arindamsen95NetworkSpeedProxy, g_object_unref)
#endif

void arindamsen95_network_speed_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Arindamsen95NetworkSpeed *arindamsen95_network_speed_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
Arindamsen95NetworkSpeed *arindamsen95_network_speed_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void arindamsen95_network_speed_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Arindamsen95NetworkSpeed *arindamsen95_network_speed_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
Arindamsen95NetworkSpeed *arindamsen95_network_speed_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON (arindamsen95_network_speed_skeleton_get_type ())
#define ARINDAMSEN95_NETWORK_SPEED_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON, Arindamsen95NetworkSpeedSkeleton))
#define ARINDAMSEN95_NETWORK_SPEED_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON, Arindamsen95NetworkSpeedSkeletonClass))
#define ARINDAMSEN95_NETWORK_SPEED_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON, Arindamsen95NetworkSpeedSkeletonClass))
#define IS_ARINDAMSEN95_NETWORK_SPEED_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON))
#define IS_ARINDAMSEN95_NETWORK_SPEED_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ARINDAMSEN95_NETWORK_SPEED_SKELETON))

typedef struct _Arindamsen95NetworkSpeedSkeleton Arindamsen95NetworkSpeedSkeleton;
typedef struct _Arindamsen95NetworkSpeedSkeletonClass Arindamsen95NetworkSpeedSkeletonClass;
typedef struct _Arindamsen95NetworkSpeedSkeletonPrivate Arindamsen95NetworkSpeedSkeletonPrivate;

struct _Arindamsen95NetworkSpeedSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  Arindamsen95NetworkSpeedSkeletonPrivate *priv;
};

struct _Arindamsen95NetworkSpeedSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType arindamsen95_network_speed_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Arindamsen95NetworkSpeedSkeleton, g_object_unref)
#endif

Arindamsen95NetworkSpeed *arindamsen95_network_speed_skeleton_new (void);


G_END_DECLS

#endif /* __NETWORKSPEEDDBUS_H__ */
